### ISSUE TITLE
node-red crashes on blank node

### ISSUE THREAD

**Issue by vossilius** [tzapu/node-red-contrib-blynk-websockets#17]
Hi,

have an issue with the node running on Raspberry Pi. Node-red running sluggish and log output is filled with error, close until FATAL ERROR occurs (see below).

```
...
error
close
error
close
error
close

<--- Last few GCs --->

  398621 ms: Scavenge 241.0 (280.7) -> 241.0 (280.7) MB, 44.1 / 0 ms (+ 13.3 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  401638 ms: Mark-sweep 241.0 (280.7) -> 240.7 (280.7) MB, 3017.3 / 1 ms (+ 19.3 ms in 2 steps since start of marking, biggest step 13.3 ms) [last resort gc].
  404543 ms: Mark-sweep 240.7 (280.7) -> 240.7 (280.7) MB, 2904.0 / 1 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x48c6d639 <JS Object>
    1: initAsClient [/home/pi/.node-red/node_modules/node-red-contrib-blynk-websockets/node_modules/ws/lib/WebSocket.js:~571] [pc=0x6591dfb8] (this=0x24545249 <a WebSocket with map 0x3e4988e9>,address=0x2e44a9b9 <String[35]: ws://blynk-cloud.com:8082/websocket>,protocols=0x575f9c75 <JS Array[0]>,options=0x48c080dd <undefined>)
    3: new constructor(aka WebSocket) [/home/pi/.node-red/node_modules/n...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted
```

**Comment by mayankraichura** [comment]
Hi,

I'm having same issue. If try to add any node and deploy - it hangs with following message on journalctl

```
Apr 14 11:01:35 officepi Node-RED[3054]: close
Apr 14 11:01:35 officepi Node-RED[3054]: error
Apr 14 11:01:35 officepi Node-RED[3054]: close
Apr 14 11:01:35 officepi Node-RED[3054]: error
Apr 14 11:01:35 officepi Node-RED[3054]: close
Apr 14 11:01:35 officepi Node-RED[3054]: error
Apr 14 11:01:35 officepi Node-RED[3054]: close
Apr 14 11:01:35 officepi Node-RED[3054]: error
Apr 14 11:01:35 officepi Node-RED[3054]: close
Apr 14 11:01:35 officepi Node-RED[3054]: error
Apr 14 11:01:35 officepi Node-RED[3054]: close
Apr 14 11:01:35 officepi Node-RED[3054]: error
Apr 14 11:01:35 officepi Node-RED[3054]: close
Apr 14 11:01:35 officepi Node-RED[3054]: error
Apr 14 11:01:35 officepi Node-RED[3054]: close
Apr 14 11:01:35 officepi Node-RED[3054]: error
Apr 14 11:01:35 officepi Node-RED[3054]: close
Apr 14 11:01:35 officepi Node-RED[3054]: error
Apr 14 11:01:35 officepi Node-RED[3054]: close
Apr 14 11:01:35 officepi Node-RED[3054]: error
```

![image](https://cloud.githubusercontent.com/assets/2023368/25035160/74d733cc-2109-11e7-9d2c-9a3973b4d4c0.png)

**Comment by vossilius** [comment]
Still, the issue is persisting:

```
> /var/services/homes/admin/.pm2/logs/node-red-error-0.log last 15 lines:
> 0|node-red |     at BlynkClientNode.login (/volume1/homes/admin/.node-red/node_modules/node-red-contrib-blynk-websockets/blynk-websockets.js:313:18)
> 0|node-red |     at WebSocket.<anonymous> (/volume1/homes/admin/.node-red/node_modules/node-red-contrib-blynk-websockets/blynk-websockets.js:220:19)
> 0|node-red |     at emitNone (events.js:67:13)
> 0|node-red |     at WebSocket.emit (events.js:166:7)
> 0|node-red |     at WebSocket.establishConnection (/volume1/homes/admin/.node-red/node_modules/node-red-contrib-blynk-websockets/node_modules/ws/lib/WebSocket.js:887:8)
> 0|node-red |     at ClientRequest.upgrade (/volume1/homes/admin/.node-red/node_modules/node-red-contrib-blynk-websockets/node_modules/ws/lib/WebSocket.js:778:25)
```
Have had a power outage but my UPS downed the server gracefully. Booting things up again and node-red is hanging as this node is making trouble again. Very unreliable.

**Comment by kaniick** [comment]
I am receiving the same errors ... Node-red crashes while this modules is enabled.
